import { useEffect, useState } from "react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { aegisApi, type DownstreamOutput } from "@/lib/aegisApi";
import { ArrowLeft, ArrowRight, CircleAlert, LockKeyhole, ShieldAlert } from "lucide-react";

export default function DownstreamOutput() {
  const [output, setOutput] = useState<DownstreamOutput | null>(null);
  useEffect(() => { void aegisApi.getDownstream().then(setOutput).catch(() => setOutput(null)); }, []);
  return <AppShell><main className="case-workspace">
    <Link href="/judge" className="back-link"><ArrowLeft size={15} /> Judge Mode</Link>
    <header className="case-header"><div className="case-heading-grid"><div><p className="eyebrow">Downstream value / controlled proof</p><h1>Price intelligence<br /><span className="bone-emphasis">refuses untrusted output.</span></h1><p className="case-description">This consumer view is backed by the canonical silent-corruption fixture and deterministic AEGIS decision modules. It is not a live provider product record.</p></div><div className="state-block"><span className="eyebrow">Consumer status</span><strong>{output?.output.status ?? "UNAVAILABLE"}</strong><p>{output?.output.consumer_message ?? "The canonical output boundary is unavailable."}</p></div></div></header>
    {output ? <><section className="contract-summary"><div><span className="source-pill source-replay">TEST DOUBLE / CONTROLLED REPLAY</span><h2>{output.product.title}</h2><p className="case-target">Product reference: {output.product.product_id}</p></div><div className="contract-columns"><div><span className="summary-label">Expected trusted value</span><p><b>{output.product.expected_price}</b><small>Canonical semantic expectation</small></p></div><div><span className="summary-label">Observed candidate value</span><p className="case-config-detail"><b>{output.product.observed_price}</b><small>Unverified controlled candidate</small></p></div></div></section>
    <section className="ledger-panel"><div className="panel-heading"><div><span className="eyebrow">Evidence decides</span><h2>Why this value <span className="bone-emphasis">cannot ship.</span></h2></div><span className="source-pill source-replay">controlled replay</span></div><div className="ledger-spine">{output.verification.checks.map((check) => <article className="ledger-event" key={check.channel}><span className="ledger-node">{check.status === "PASS" ? <LockKeyhole size={15} /> : <CircleAlert size={15} />}</span><div className="ledger-copy"><span className="ledger-type">{check.channel.replaceAll("_", " ")}</span><p>{check.status}{check.critical ? " · critical contradiction" : ""}</p><small className="event-ref">{check.message}</small></div><time>{check.status}</time></article>)}</div></section>
    <section className="case-semantic-workspace"><div className="panel-heading"><div><span className="eyebrow">Safety decision</span><h2>Verification {output.verification.status} → Risk {output.risk.decision} → Commit {output.commit.eligibility}</h2></div><span className="source-pill source-local"><ShieldAlert size={13} /> data shipped: no</span></div><p className="controlled-graph-note"><LockKeyhole size={15} /> {output.commit.block_reasons.join(" · ")}</p><Link href="/judge" className="outline-button">Return to provider evidence and replay <ArrowRight size={16} /></Link></section></> : <section className="evidence-empty-hero"><CircleAlert size={24} /><div><span className="eyebrow">Output boundary unavailable</span><h2>No downstream claim can be made.</h2><p>AEGIS will not render a consumer value without the canonical controlled decision projection.</p></div></section>}
  </main></AppShell>;
}
