"""AEGIS Mission 003: collection, observation, detection, diagnosis, and repair request."""

from .adapter import AdapterError, BrightDataCliAdapter, CommandResult
from .contracts import default_extraction_contract
from .detection import evaluate_detection
from .diagnosis import (
    Diagnosis,
    DiagnosisCertainty,
    DiagnosisContext,
    DiagnosisProvenance,
    DiagnosisStatus,
    DeterministicDiagnostician,
    FailureClass,
    HealingRequester,
    NoExecutionRepairBoundary,
    RepairAttemptHandle,
    RepairAttemptState,
    RepairBoundaryProvenance,
    RepairRequest,
    RepairRequestStatus,
    StructuredModelDiagnostician,
    TestDoubleDiagnostician,
    build_repair_request,
    diagnose_deterministically,
)
from .models import (
    CollectionHandle,
    CollectionMode,
    CollectionResult,
    CollectionState,
    CollectorHandle,
    CollectorRequest,
    DetectionResult,
    DetectionSignal,
    ExtractionContract,
    FieldContract,
    Observation,
    ProviderProvenance,
)
from .test_double import DeterministicBrightDataTestDouble, TestDoubleScenario

__all__ = [
    "AdapterError",
    "BrightDataCliAdapter",
    "CollectionHandle",
    "CollectionMode",
    "CollectionResult",
    "CollectionState",
    "CollectorHandle",
    "CollectorRequest",
    "CommandResult",
    "default_extraction_contract",
    "DetectionResult",
    "DetectionSignal",
    "DeterministicBrightDataTestDouble",
    "Diagnosis",
    "DiagnosisCertainty",
    "DiagnosisContext",
    "DiagnosisProvenance",
    "DiagnosisStatus",
    "DeterministicDiagnostician",
    "evaluate_detection",
    "ExtractionContract",
    "FailureClass",
    "FieldContract",
    "HealingRequester",
    "NoExecutionRepairBoundary",
    "Observation",
    "ProviderProvenance",
    "RepairAttemptHandle",
    "RepairAttemptState",
    "RepairBoundaryProvenance",
    "RepairRequest",
    "RepairRequestStatus",
    "StructuredModelDiagnostician",
    "TestDoubleDiagnostician",
    "TestDoubleScenario",
    "build_repair_request",
    "diagnose_deterministically",
]
