"""AEGIS Mission 004: bounded Bright Data healing and unverified candidates."""

from .adapter import (
    AdapterError,
    BrightDataCliAdapter,
    CommandResult,
    build_heal_command,
    build_heal_prompt,
)
from .contracts import default_extraction_contract
from .detection import evaluate_detection
from .diagnosis import (
    Diagnosis,
    DiagnosisCertainty,
    DiagnosisContext,
    DiagnosisProvenance,
    DiagnosisStatus,
    DeterministicDiagnostician,
    FailureClass,
    HealingRequester,
    NoExecutionRepairBoundary,
    RepairAttemptHandle,
    RepairAttemptState,
    RepairBoundaryProvenance,
    RepairRequest,
    RepairRequestStatus,
    StructuredModelDiagnostician,
    TestDoubleDiagnostician,
    build_repair_request,
    diagnose_deterministically,
)
from .healing import (
    HealHandle,
    HealOperationResult,
    HealProviderEnvelope,
    HealState,
    RepairCandidate,
    VerificationStatus,
)
from .models import (
    CollectionHandle,
    CollectionMode,
    CollectionResult,
    CollectionState,
    CollectorHandle,
    CollectorRequest,
    DetectionResult,
    DetectionSignal,
    ExtractionContract,
    FieldContract,
    Observation,
    ProviderProvenance,
)
from .test_double import (
    DeterministicBrightDataHealingTestDouble,
    DeterministicBrightDataTestDouble,
    HealTestDoubleScenario,
    TestDoubleScenario,
)

__all__ = [
    "AdapterError",
    "BrightDataCliAdapter",
    "CollectionHandle",
    "CollectionMode",
    "CollectionResult",
    "CollectionState",
    "CollectorHandle",
    "CollectorRequest",
    "CommandResult",
    "default_extraction_contract",
    "DetectionResult",
    "DetectionSignal",
    "DeterministicBrightDataHealingTestDouble",
    "DeterministicBrightDataTestDouble",
    "Diagnosis",
    "DiagnosisCertainty",
    "DiagnosisContext",
    "DiagnosisProvenance",
    "DiagnosisStatus",
    "DeterministicDiagnostician",
    "evaluate_detection",
    "ExtractionContract",
    "FailureClass",
    "FieldContract",
    "HealHandle",
    "HealOperationResult",
    "HealProviderEnvelope",
    "HealState",
    "HealingRequester",
    "HealTestDoubleScenario",
    "NoExecutionRepairBoundary",
    "Observation",
    "ProviderProvenance",
    "RepairAttemptHandle",
    "RepairAttemptState",
    "RepairBoundaryProvenance",
    "RepairCandidate",
    "RepairRequest",
    "RepairRequestStatus",
    "StructuredModelDiagnostician",
    "TestDoubleDiagnostician",
    "TestDoubleScenario",
    "VerificationStatus",
    "build_heal_command",
    "build_heal_prompt",
    "build_repair_request",
    "diagnose_deterministically",
]
